-- MySQL Script generated by MySQL Workbench
-- Thu Dec  5 19:49:56 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todolist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todolist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todolist` DEFAULT CHARACTER SET utf8 ;
USE `todolist` ;

-- -----------------------------------------------------
-- Table `todolist`.`planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolist`.`planos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(40) NOT NULL,
  `descricao` TEXT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todolist`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolist`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(80) NOT NULL,
  `foto` VARCHAR(40) NULL DEFAULT 'default.jpg',
  `nivel` INT(1) NOT NULL,
  `token` CHAR(32) NULL,
  `data_cadastro` DATETIME NOT NULL,
  `plano_id` INT NOT NULL,
  PRIMARY KEY (`id`, `plano_id`),
  INDEX `fk_usuarios_planos1_idx` (`plano_id` ASC),
  CONSTRAINT `fk_usuarios_planos1`
    FOREIGN KEY (`plano_id`)
    REFERENCES `todolist`.`planos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todolist`.`tarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolist`.`tarefas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tarefa` VARCHAR(200) NOT NULL,
  `descricao` TEXT NULL,
  `prioridade` CHAR(10) NOT NULL,
  `status` INT(1) NOT NULL,
  `usuario_id` INT NOT NULL,
  `data_cadatro` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tarefas_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_tarefas_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `todolist`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todolist`.`paginas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolist`.`paginas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(200) NOT NULL,
  `slug` VARCHAR(200) NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
